import { Inter } from 'next/font/google'
import './globals.css'
import Navber from '@/components/Nav'
import { ThemeProvider } from '@/lib/Theme-povider'
const inter = Inter({ subsets: ['latin'] })
import { Toaster } from '@/components/ui/toaster'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navber />
          {children}
          <Toaster/>
        </ThemeProvider>
      </body>
    </html>
  )
}
